[build-system]
requires = ['setuptools >= 61.0']
build-backend = 'setuptools.build_meta'

[project]
name = 'Envy'
version = '3.0.0'
readme = 'README.md'
dependencies = [
    'PySide6<7',
    'qasync<1',
    'websockets<14',
    'pydantic<3'
]
requires-python = '>=3.9'
authors = [
    {name = 'Nathan Vandevoort', email = 'nathan.v.2021@gmail.com'},
]

[project.optional-dependencies]
dev = [
    'black',
    'python-semantic-release>=9',
]

[tool.semantic_release]
version_toml = ['pyproject.toml:project.version']
version_variables = ["envy/__init__.py:__version__"]

[tool.black]
skip-string-normalization = true
line-length = 120

[tool.isort]
profile = "black"
